name: CI tests

on:
  push:
    branches:
      - main
    paths:
      - 'wind_ae/**'
      - requirements.txt
      - pyproject.toml
      - setup.py
      - MANIFEST.in
      - .github/workflows/python-pkg.yml
  pull_request:
    branches:
      - '*'
    paths:
      - 'wind_ae/**'
      - requirements.txt
      - pyproject.toml
      - setup.py
      - MANIFEST.in
      - .github/workflows/python-pkg.yml

jobs:
  build:
    runs-on: macos-latest

    strategy:
      fail-fast: false
      matrix:
        python-version: ["3.13"]

    steps:
    - uses: actions/checkout@v4

    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ matrix.python-version }}

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        python -m pip install pytest pytest-cov
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Test with pytest
      run: |
        pytest --cov

    - name: Coveralls GitHub Action
      uses: coverallsapp/github-action@v2
